/* Generated by Nim Compiler v2.2.4 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NI tyArray__bmYSvqlC9bgO9aJvGjLCqYpg[1024];
typedef NIM_BOOL tyArray__6YXfYAWX9amAltRi59bxJtsQ[32];
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, test__test_u33)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(void, testtest__test_u32)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3851)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsUsersatsmacosatsdotchoosenimatstoolchainsatsnimminus2dot2dot4atslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_3 = { 11 | NIM_STRLIT_FLAG, "Hello world" };
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_5 = { 8 | NIM_STRLIT_FLAG, "test1234" };
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_7 = { 9 | NIM_STRLIT_FLAG, "Xin ch\303\240o" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_9 = { 7 | NIM_STRLIT_FLAG, "9944745" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_11 = { 10 | NIM_STRLIT_FLAG, "2222222211" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_13 = { 7 | NIM_STRLIT_FLAG, "9900001" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_15 = { 6 | NIM_STRLIT_FLAG, "585963" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_17 = { 10 | NIM_STRLIT_FLAG, "9201897189" };
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_19 = { 9 | NIM_STRLIT_FLAG, "991111111" };
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_21 = { 9 | NIM_STRLIT_FLAG, "988888890" };
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_23 = { 9 | NIM_STRLIT_FLAG, "999999999" };
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_25 = { 9 | NIM_STRLIT_FLAG, "300000000" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_27 = { 10 | NIM_STRLIT_FLAG, "-327777778" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__ipcYmBC9bj9a1BW35ABoB1Kw_29 = { 3 | NIM_STRLIT_FLAG, "305" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_2 = {{11, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_3}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_4 = {{8, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_5}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_6 = {{9, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_7}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_8 = {{7, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_9}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_10 = {{10, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_11}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_12 = {{7, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_13}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_14 = {{6, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_15}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_16 = {{10, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_17}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_18 = {{9, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_19}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_20 = {{9, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_21}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_22 = {{9, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_23}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_24 = {{9, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_25}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_26 = {{10, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_27}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ipcYmBC9bj9a1BW35ABoB1Kw_28 = {{3, (NimStrPayload*)&TM__ipcYmBC9bj9a1BW35ABoB1Kw_29}}
;
N_LIB_PRIVATE tySequence__sM4lkSb7zS6F7OVMvW9cffQ BUS__test_u9;
N_LIB_PRIVATE tyArray__bmYSvqlC9bgO9aJvGjLCqYpg RAM__test_u4;
N_LIB_PRIVATE tyArray__6YXfYAWX9amAltRi59bxJtsQ Pins__test_u10;
N_LIB_PRIVATE NI otest__test_u34 = ((NI)8748199);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4429;
N_LIB_PRIVATE N_NIMCALL(void, test__test_u33)(void) {
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_4, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_6, 1);
}
N_LIB_PRIVATE N_NIMCALL(void, testtest__test_u32)(void) {
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_4, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_6, 1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4429);
	return result;
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsUsersatsmacosatsdotchoosenimatstoolchainsatsnimminus2dot2dot4atslibatssystemdotnim_Init000();
	(*inner)();
#else
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsUsersatsmacosatsdotchoosenimatstoolchainsatsnimminus2dot2dot4atslibatssystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	NimStringV2 colontmpD_;
	tyArray__nHXaesL0DJZHyVS07ARPRA T2_;
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	BUS__test_u9.len = 0; BUS__test_u9.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_2, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_4, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_6, 1);
	test__test_u33();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD_ = dollar___systemZdollars_u14(otest__test_u34);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0] = colontmpD_;
	echoBinSafe(T2_, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_8, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_4, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_6, 1);
	testtest__test_u32();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_10, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_12, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_14, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_16, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_18, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_20, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_22, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_24, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_26, 1);
	echoBinSafe(TM__ipcYmBC9bj9a1BW35ABoB1Kw_28, 1);
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___system_u3851(BUS__test_u9);
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

